### register
POST http://localhost:8000/api/register
Accept: application/json
Content-Type: application/json

{
    "name": "muhajir",
    "email": "muhajir@mail.com",
    "password": "password",
    "password_confirmation": "password"
}


### create new product
POST http://localhost:8000/api/products
Accept: application/json
Authorization: Bearer 3|lxvLYO7mJ8TcL3ykKTNhh7PzWGD200ZxbSQ0DfDI
Content-Type: application/json

{
    "name": "Sabun",
    "price": 2000
}

### login
POST http://localhost:8000/api/login
Accept: application/json
Content-Type: application/json

{
    "email": "muhajir@mail.com",
    "password": "password"
}


### logout
POST http://localhost:8000/api/logout
Accept: application/json
Authorization: Bearer 7|XkclMYrcqbtLPT7XjDbZnAg76X6Dqjn5fbcJx793
